version: '3.7'
services:
    db:
        container_name: 'database-healthFazenda'
        image: mysql:latest
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: healthFazenda
